### ISSUE TITLE
why synchronized?

### ISSUE THREAD

**Issue by mox601** [Cybion-Italy/socialeyeser#7]
``` java
FixedSizeWindow...
    public synchronized double pushFeature(EmittedFeature newestFeature) {
```

What is the meaning of the double returned?

**Comment by sergiodaia** [comment]
is the average value for the observed feature in the window.

**Comment by sergiodaia** [comment]
the synchronized was intended for multithreaded environments;
since the underlying datastructure is either a linked list or a queue, synchronized access was a must
